

# services:
#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: rootuser
#       POSTGRES_DB: testdb
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#         DATABASE_URL = "postgresql+psycopg2://postgres:rootuser@localhost:5432/testdb"
#     volumes:
#       - .:/app  # mounts current folder inside container (for dev)
#     command: uvicorn main:app --host 0.0.0.0 --port 8000

# volumes:
#   pgdata:



# version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootuser
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:rootuser@db:5432/testdb
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000